name: Interactive ndows Server 2022 RDP v2

on:
  workflow_dispatch: # Cho phép chạy workflow thủ công từ trang Actions

jobs:
  rdp_access:
    runs-on: windows-2022 # Chỉ định runner là Windows Server 2022

    steps:
    - name: Setup ngrok Tunnel for RDP
      run: |
        # Tải ngrok v3
        Invoke-WebRequest -Uri https://ngrok.com/download/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath .

        # Xác thực ngrok v3 (Vẫn sử dụng SECRET NGROK_AUTH_TOKEN của bạn)
        .\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

        # Khởi động ngrok v3 tunnel cho cổng RDP (3389)
        Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389 --log=stdout" -NoNewWindow -PassThru | Out-Null

        # Chờ ngrok khởi động và lấy địa chỉ công khai
        Start-Sleep -Seconds 15 # Tăng thời gian chờ để đảm bảo ngrok khởi động đầy đủ
        $ngrok_status = Invoke-WebRequest -Uri "http://localhost:4040/api/tunnels" -UseBasicParsing
        $ngrok_json = ConvertFrom-Json $ngrok_status.Content
        $ngrok_url = $ngrok_json.tunnels[0].public_url
        Write-Host "Remote Desktop available at: $ngrok_url"

        # Hiển thị thông tin đăng nhập RDP mặc định của GitHub Actions runner
        Write-Host "Username for RDP: runneradmin"
        Write-Host "Please check the log for the generated password (usually in the initial setup steps or in a variable)."


    - name: Keep RDP session alive (Important!)
      run: |
        Write-Host "Keeping session alive for about 5 hours 50 minutes..."
        Start-Sleep -Seconds 20700 # ~ 5 giờ 45 phút (tối đa 6 giờ)
        Write-Host "Session is about to end."
      timeout-minutes: 350 # Đặt tối đa 350 phút để an toàn hơn, không vượt quá giới hạn 360 phút của GitHub
